### ISSUE TITLE
Decide what ExceptionGroup.args should be

### ISSUE THREAD

**Issue by njsmith** [python-trio/exceptiongroup#8]
Exceptions in general have an unusual convention where you can pass any positional arguments that you want to the constructor, and they all get stashed as `.args`, and `str(exc)` returns `str(exc.args[0]) if len(exc.args) == 1 else str(exc.args)`. This behavior is all defined in `BaseException`.

Most exceptions don't actually take multiple arguments and assign them meaning. But actually, `OSError` does, so maybe that should be our precedent?

It looks like `OSError` puts all of its arguments into `.args`, but then overrides `__str__` to be something more sensible.

**Comment by WindSoilder** [comment]
Maybe we can make `ExceptionGroup` act as the same way, just put all arguments to `.args`, and document out the order of arguments.
If user pass too many arguments, we can just omit them like other `exception` does.

**Comment by njsmith** [comment]
Fixed in #12
