### ISSUE TITLE
Should we use black formatter for the code here?

### ISSUE THREAD

**Issue by WindSoilder** [python-trio/exceptiongroup#9]
Inpired by [Switch to black](https://github.com/python-trio/trio/pull/768), Maybe it's better to use `black` for the project now?

**Comment by oremanj** [comment]
I've been developing locally with black and mypy and it's a joy. I would love to see the Trio projects adopt them. I'm not sure if it makes sense for some of the Trio repositories to be on black and others on yapf though - @njsmith, what do you think?

**Comment by njsmith** [comment]
Supposedly this project is already using black, as a kind of experiment, but like all good experiments I screwed it up. Closing this in favor of #11 :-)
